apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app.kubernetes.io/name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-deployment
    spec:
      containers:
        - name: payment-service
          image: payment-service
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: payment-config
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: payment-database
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
